name: ht_authentication_repository
description: A Very Good Project created by Very Good CLI.
publish_to: none
repository: https://github.com/headlines-toolkit/ht-authentication-repository 

environment:
  sdk: ^3.7.0

dependencies: 
  ht_authentication_client:
    git:
      url: https://github.com/headlines-toolkit/ht-authentication-client.git
      ref: main
      
dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0
