name: ht_authentication_repository
description: A Flutter package for managing authentication using the Headlines Toolkit, providing a standardized interface for user registration, login, logout, and more.
publish_to: none
repository: https://github.com/headlines-toolkit/ht-authentication-repository 

environment:
  sdk: ^3.7.0

dependencies: 
  flutter:
    sdk: flutter
  ht_authentication_client:
    git:
      url: https://github.com/headlines-toolkit/ht-authentication-client.git
  ht_kv_storage_service:
    git:
      url: https://github.com/headlines-toolkit/ht-kv-storage-service.git
  rxdart: ^0.28.0
      
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
